version: 2
jobs:
  build-apps:
    docker:
      - image: circleci/golang:1.19
    steps:
      - checkout
      - run: cd apps/svc-one && go build
      - run: cd apps/client-api && go build

workflows:
  version: 2
  all:
    jobs:
      - build-apps

