receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: error
  otlp:
    endpoint: "otel-collector:4317"
    insecure: true

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlp, logging]
