receivers:
  opencensus:
  jaeger:
    protocols:
      grpc:
      thrift_http:
      thrift_compact:
      thrift_binary:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "otel-collector:4317"
    insecure: true

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [otlp, logging]
    metrics:
      receivers: [opencensus]
      processors: [batch]
      exporters: [otlp, logging]
